version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  findata:
    build:
      context: ./app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DEBUG: "False"
      DB_NAME: "admin"
      DB_USER: "admin"
      DB_PASSWORD: "admin"
      DB_HOST: "postgres"
      DB_PORT: 5432
    volumes:
      - static_volume:/app/static

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - findata

volumes:
  static_volume: