# Generated by Django 4.1.3 on 2023-11-16 09:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200, verbose_name='Название организации')),
                ('chairman_directors', models.TextField(max_length=200, verbose_name='Председатель Совета директоров')),
                ('chairman_board', models.TextField(max_length=200, verbose_name='Председатель Правления')),
                ('board_directors', models.TextField(max_length=1000, verbose_name='Совет директоров')),
                ('board_members', models.CharField(max_length=1000, verbose_name='Члены правления')),
                ('cheif_accountant', models.CharField(max_length=200, verbose_name='Главный бухгалтер')),
                ('bin', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only 0-9 are allowed.', 'Invalid Number')])),
                ('address', models.CharField(max_length=200, verbose_name='Адрес (город, улица, дом, квартира)')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=200, null=True, region=None, verbose_name='Факс')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator(message='Invalid Email')], verbose_name='E-mail')),
                ('web_site', models.CharField(max_length=200, verbose_name='Web-сайт')),
                ('level_of_organization', models.CharField(max_length=200, verbose_name='Уровень организации')),
                ('custodian', models.TextField(max_length=500, verbose_name='Кастодиан')),
                ('broker_dealers', models.TextField(max_length=1000, verbose_name='Брокеры-дилеры')),
                ('org_logo', models.ImageField(blank=True, upload_to='', verbose_name='Фото организации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Куратор')),
            ],
        ),
    ]
